version: '3.9'  # or any appropriate version you need
services:
  # Your services here

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db/medical_db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medical_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
